/**
 * Distribution Network Service API
 * API documentation for the Distribution Network's API.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: christoph.schranz@salzburgresearcht.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ClientAppBody } from '../model/clientAppBody';
import { ClientApps } from '../model/clientApps';
import { Status } from '../model/status';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ClientAppRequestService {

    protected basePath = 'https://iasset.salzburgresearch.at/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Return a specific client app that belongs to a system
     * 
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param clientName client app name
     * @param authorization Bearer token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkClientAppsPersonIdSystemClientNameGet(personId: number, system: string, clientName: string, authorization: string, observe?: 'body', reportProgress?: boolean): Observable<ClientApps>;
    public distributionnetworkClientAppsPersonIdSystemClientNameGet(personId: number, system: string, clientName: string, authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemClientNameGet(personId: number, system: string, clientName: string, authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemClientNameGet(personId: number, system: string, clientName: string, authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkClientAppsPersonIdSystemClientNameGet.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkClientAppsPersonIdSystemClientNameGet.');
        }

        if (clientName === null || clientName === undefined) {
            throw new Error('Required parameter clientName was null or undefined when calling distributionnetworkClientAppsPersonIdSystemClientNameGet.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkClientAppsPersonIdSystemClientNameGet.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ClientApps>('get',`${this.basePath}/distributionnetwork/client_apps/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}/${encodeURIComponent(String(clientName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Return all client apps that belong to a system
     * 
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param authorization Bearer token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkClientAppsPersonIdSystemGet(personId: number, system: string, authorization: string, observe?: 'body', reportProgress?: boolean): Observable<ClientApps>;
    public distributionnetworkClientAppsPersonIdSystemGet(personId: number, system: string, authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemGet(personId: number, system: string, authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemGet(personId: number, system: string, authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkClientAppsPersonIdSystemGet.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkClientAppsPersonIdSystemGet.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkClientAppsPersonIdSystemGet.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ClientApps>('get',`${this.basePath}/distributionnetwork/client_apps/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a new client app for a system that belongs to a person.
     * 
     * @param body A client app object to create.
     * @param authorization Bearer token
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkClientAppsPersonIdSystemPost(body: ClientAppBody, authorization: string, personId: number, system: string, observe?: 'body', reportProgress?: boolean): Observable<ClientApps>;
    public distributionnetworkClientAppsPersonIdSystemPost(body: ClientAppBody, authorization: string, personId: number, system: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemPost(body: ClientAppBody, authorization: string, personId: number, system: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemPost(body: ClientAppBody, authorization: string, personId: number, system: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPost.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPost.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPost.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ClientApps>('post',`${this.basePath}/distributionnetwork/client_apps/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create or update a client app for a system that belongs to a person.
     * 
     * @param body A client app object to create.
     * @param authorization Bearer token
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkClientAppsPersonIdSystemPut(body: ClientAppBody, authorization: string, personId: number, system: string, observe?: 'body', reportProgress?: boolean): Observable<ClientApps>;
    public distributionnetworkClientAppsPersonIdSystemPut(body: ClientAppBody, authorization: string, personId: number, system: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemPut(body: ClientAppBody, authorization: string, personId: number, system: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ClientApps>>;
    public distributionnetworkClientAppsPersonIdSystemPut(body: ClientAppBody, authorization: string, personId: number, system: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPut.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPut.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPut.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkClientAppsPersonIdSystemPut.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ClientApps>('put',`${this.basePath}/distributionnetwork/client_apps/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a client app from a system
     * 
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param clientName stream app name
     * @param authorization Bearer token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete(personId: number, system: string, clientName: string, authorization: string, observe?: 'body', reportProgress?: boolean): Observable<Status>;
    public distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete(personId: number, system: string, clientName: string, authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Status>>;
    public distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete(personId: number, system: string, clientName: string, authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Status>>;
    public distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete(personId: number, system: string, clientName: string, authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete.');
        }

        if (clientName === null || clientName === undefined) {
            throw new Error('Required parameter clientName was null or undefined when calling distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkDeleteClientAppPersonIdSystemClientNameDelete.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Status>('delete',`${this.basePath}/distributionnetwork/delete_client_app/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}/${encodeURIComponent(String(clientName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
