/**
 * Distribution Network Service API
 * API documentation for the Distribution Network's API.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: christoph.schranz@salzburgresearcht.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Empty } from '../model/empty';
import { Status } from '../model/status';
import { StreamAppStatistic } from '../model/streamAppStatistic';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class StreamAppControlRequestService {

    protected basePath = 'https://iasset.salzburgresearch.at/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Deploy an existing stream app of a system.
     * 
     * @param body An empty object.
     * @param authorization Bearer token
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param streamName stream app name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'body', reportProgress?: boolean): Observable<Status>;
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Status>>;
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Status>>;
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost.');
        }

        if (streamName === null || streamName === undefined) {
            throw new Error('Required parameter streamName was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Status>('post',`${this.basePath}/distributionnetwork/stream_app_deploy/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}/${encodeURIComponent(String(streamName))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deploy an existing stream app of a system, stop and redeploy if it already runs.
     * 
     * @param body An empty object.
     * @param authorization Bearer token
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param streamName stream app name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'body', reportProgress?: boolean): Observable<Status>;
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Status>>;
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Status>>;
    public distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut.');
        }

        if (streamName === null || streamName === undefined) {
            throw new Error('Required parameter streamName was null or undefined when calling distributionnetworkStreamAppDeployPersonIdSystemStreamNamePut.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Status>('put',`${this.basePath}/distributionnetwork/stream_app_deploy/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}/${encodeURIComponent(String(streamName))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Return the statistic of a specific stream app that belongs to a system
     * 
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param streamName stream app name
     * @param authorization Bearer token
     * @param statistic Return &#x27;status&#x27; (default), &#x27;is_running&#x27;, &#x27;stats&#x27;, &#x27;short_stats&#x27;, &#x27;logs_{number_of_logs}&#x27; or &#x27;config&#x27;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet(personId: number, system: string, streamName: string, authorization: string, statistic?: any, observe?: 'body', reportProgress?: boolean): Observable<StreamAppStatistic>;
    public distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet(personId: number, system: string, streamName: string, authorization: string, statistic?: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StreamAppStatistic>>;
    public distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet(personId: number, system: string, streamName: string, authorization: string, statistic?: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StreamAppStatistic>>;
    public distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet(personId: number, system: string, streamName: string, authorization: string, statistic?: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet.');
        }

        if (streamName === null || streamName === undefined) {
            throw new Error('Required parameter streamName was null or undefined when calling distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkStreamAppStatisticPersonIdSystemStreamNameGet.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (statistic !== undefined && statistic !== null) {
            queryParameters = queryParameters.set('statistic', <any>statistic);
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<StreamAppStatistic>('get',`${this.basePath}/distributionnetwork/stream_app_statistic/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}/${encodeURIComponent(String(streamName))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Stop an existing stream app of a system.
     * 
     * @param body An empty object.
     * @param authorization Bearer token
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param streamName stream app name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkStreamAppStopPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'body', reportProgress?: boolean): Observable<Status>;
    public distributionnetworkStreamAppStopPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Status>>;
    public distributionnetworkStreamAppStopPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Status>>;
    public distributionnetworkStreamAppStopPersonIdSystemStreamNamePost(body: Empty, authorization: string, personId: number, system: string, streamName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling distributionnetworkStreamAppStopPersonIdSystemStreamNamePost.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkStreamAppStopPersonIdSystemStreamNamePost.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkStreamAppStopPersonIdSystemStreamNamePost.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkStreamAppStopPersonIdSystemStreamNamePost.');
        }

        if (streamName === null || streamName === undefined) {
            throw new Error('Required parameter streamName was null or undefined when calling distributionnetworkStreamAppStopPersonIdSystemStreamNamePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Status>('post',`${this.basePath}/distributionnetwork/stream_app_stop/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}/${encodeURIComponent(String(streamName))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
