/**
 * Distribution Network Service API
 * API documentation for the Distribution Network's API.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: christoph.schranz@salzburgresearcht.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Status } from '../model/status';
import { SystemBody } from '../model/systemBody';
import { Systems } from '../model/systems';
import { SystemsAndAdmins } from '../model/systemsAndAdmins';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SystemRequestService {

    protected basePath = 'https://iasset.salzburgresearch.at/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Delete a system from a company that belongs to a person
     * 
     * @param personId User ID from the identity service
     * @param system identifier with &#x27;_&#x27; as level separator
     * @param authorization Bearer token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkDeleteSystemPersonIdSystemDelete(personId: string, system: string, authorization: string, observe?: 'body', reportProgress?: boolean): Observable<Status>;
    public distributionnetworkDeleteSystemPersonIdSystemDelete(personId: string, system: string, authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Status>>;
    public distributionnetworkDeleteSystemPersonIdSystemDelete(personId: string, system: string, authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Status>>;
    public distributionnetworkDeleteSystemPersonIdSystemDelete(personId: string, system: string, authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkDeleteSystemPersonIdSystemDelete.');
        }

        if (system === null || system === undefined) {
            throw new Error('Required parameter system was null or undefined when calling distributionnetworkDeleteSystemPersonIdSystemDelete.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkDeleteSystemPersonIdSystemDelete.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Status>('delete',`${this.basePath}/distributionnetwork/delete_system/${encodeURIComponent(String(personId))}/${encodeURIComponent(String(system))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Return all systems that belong to a person
     * 
     * @param personId User ID from the identity service
     * @param authorization Bearer token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkSystemsByPersonPersonIdGet(personId: string, authorization: string, observe?: 'body', reportProgress?: boolean): Observable<Systems>;
    public distributionnetworkSystemsByPersonPersonIdGet(personId: string, authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Systems>>;
    public distributionnetworkSystemsByPersonPersonIdGet(personId: string, authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Systems>>;
    public distributionnetworkSystemsByPersonPersonIdGet(personId: string, authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkSystemsByPersonPersonIdGet.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkSystemsByPersonPersonIdGet.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Systems>('get',`${this.basePath}/distributionnetwork/systems_by_person/${encodeURIComponent(String(personId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a new system for a company that belongs to a person. Creates also the corresponding Kafka topics.
     * 
     * @param body A system object to create, functional part of a company
     * @param authorization Bearer token
     * @param personId User ID from the identity service
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkSystemsByPersonPersonIdPost(body: SystemBody, authorization: string, personId: string, observe?: 'body', reportProgress?: boolean): Observable<SystemsAndAdmins>;
    public distributionnetworkSystemsByPersonPersonIdPost(body: SystemBody, authorization: string, personId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SystemsAndAdmins>>;
    public distributionnetworkSystemsByPersonPersonIdPost(body: SystemBody, authorization: string, personId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SystemsAndAdmins>>;
    public distributionnetworkSystemsByPersonPersonIdPost(body: SystemBody, authorization: string, personId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling distributionnetworkSystemsByPersonPersonIdPost.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkSystemsByPersonPersonIdPost.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkSystemsByPersonPersonIdPost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SystemsAndAdmins>('post',`${this.basePath}/distributionnetwork/systems_by_person/${encodeURIComponent(String(personId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create or update a system for a company that belongs to a person. Creates also the corresponding Kafka topics.
     * 
     * @param body A system object to create, functional part of a company
     * @param authorization Bearer token
     * @param personId User ID from the identity service
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public distributionnetworkSystemsByPersonPersonIdPut(body: SystemBody, authorization: string, personId: string, observe?: 'body', reportProgress?: boolean): Observable<SystemsAndAdmins>;
    public distributionnetworkSystemsByPersonPersonIdPut(body: SystemBody, authorization: string, personId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SystemsAndAdmins>>;
    public distributionnetworkSystemsByPersonPersonIdPut(body: SystemBody, authorization: string, personId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SystemsAndAdmins>>;
    public distributionnetworkSystemsByPersonPersonIdPut(body: SystemBody, authorization: string, personId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling distributionnetworkSystemsByPersonPersonIdPut.');
        }

        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling distributionnetworkSystemsByPersonPersonIdPut.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling distributionnetworkSystemsByPersonPersonIdPut.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SystemsAndAdmins>('put',`${this.basePath}/distributionnetwork/systems_by_person/${encodeURIComponent(String(personId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
