/**
 * Distribution Network Service API
 * API documentation for the Distribution Network's API.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: christoph.schranz@salzburgresearcht.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DatastreamBody } from './datastreamBody';

export interface DatastreamsBody extends Array<DatastreamBody> { 
}