/**
 * Distribution Network Service API
 * API documentation for the Distribution Network's API.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: christoph.schranz@salzburgresearcht.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MqttBroker } from './mqttBroker';

export interface SystemBody { 
    workcenter?: string;
    station?: string;
    companyId?: number;
    kafkaServers?: string;
    description?: string;
    mqttBroker?: MqttBroker;
}