/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessPermissionRule } from './accessPermissionRule';
import { Reference } from './reference';

export interface AccessControl { 
    selectableEnvironmentAttributes?: Reference;
    defaultSubjectAttributes?: Reference;
    selectablePermissions?: Reference;
    defaultPermissions?: Reference;
    selectableSubjectAttributes?: Reference;
    defaultEnvironmentAttributes?: Reference;
    accessPermissionRules?: Array<AccessPermissionRule>;
}