/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Reference } from './reference';
import { Resource } from './resource';
import { SpecificAssetId } from './specificAssetId';

export interface AssetInformation { 
    assetKind?: AssetInformation.AssetKindEnum;
    defaultThumbnail?: Resource;
    specificAssetIds?: Array<SpecificAssetId>;
    globalAssetId?: Reference;
}
export namespace AssetInformation {
    export type AssetKindEnum = 'Instance' | 'Type';
    export const AssetKindEnum = {
        Instance: 'Instance' as AssetKindEnum,
        Type: 'Type' as AssetKindEnum
    };
}