/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptBase } from './conceptBase';
import { ConceptBaseLanguages } from './conceptBaseLanguages';

/**
 * The full description for the PropertyUnit
 */
export interface ConceptPropertyUnit extends ConceptBase { 
    dinNotation?: string;
    eceCode?: string;
    eceName?: string;
    iecClassification?: string;
    nameOfDedicatedQuantity?: string;
    nistName?: string;
    siName?: string;
    siNotation?: string;
    source?: string;
    structuredNaming?: string;
}
export namespace ConceptPropertyUnit {
}