/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptBase } from './conceptBase';
import { ConceptBaseLanguages } from './conceptBaseLanguages';

/**
 * The full description for the property value
 */
export interface ConceptPropertyValue extends ConceptBase { 
    value?: string;
    reference?: string;
    dataType?: ConceptPropertyValue.DataTypeEnum;
}
export namespace ConceptPropertyValue {
    export type DataTypeEnum = 'STRING' | 'STRING_TRANSLATABLE' | 'INTEGER_COUNT' | 'INTEGER_MEASURE' | 'INTEGER_CURRENCY' | 'REAL_COUNT' | 'REAL_MEASURE' | 'REAL_CURRENCY' | 'RATIONAL' | 'RATIONAL_MEASURE' | 'BOOLEAN' | 'DATE' | 'URL' | 'TIME' | 'TIMESTAMP';
    export const DataTypeEnum = {
        STRING: 'STRING' as DataTypeEnum,
        STRINGTRANSLATABLE: 'STRING_TRANSLATABLE' as DataTypeEnum,
        INTEGERCOUNT: 'INTEGER_COUNT' as DataTypeEnum,
        INTEGERMEASURE: 'INTEGER_MEASURE' as DataTypeEnum,
        INTEGERCURRENCY: 'INTEGER_CURRENCY' as DataTypeEnum,
        REALCOUNT: 'REAL_COUNT' as DataTypeEnum,
        REALMEASURE: 'REAL_MEASURE' as DataTypeEnum,
        REALCURRENCY: 'REAL_CURRENCY' as DataTypeEnum,
        RATIONAL: 'RATIONAL' as DataTypeEnum,
        RATIONALMEASURE: 'RATIONAL_MEASURE' as DataTypeEnum,
        BOOLEAN: 'BOOLEAN' as DataTypeEnum,
        DATE: 'DATE' as DataTypeEnum,
        URL: 'URL' as DataTypeEnum,
        TIME: 'TIME' as DataTypeEnum,
        TIMESTAMP: 'TIMESTAMP' as DataTypeEnum
    };
}