/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptBaseLanguages } from './conceptBaseLanguages';

export interface ConceptBase { 
    conceptId?: string;
    idType?: ConceptBase.IdTypeEnum;
    supplier?: string;
    nameSpace?: string;
    localName?: string;
    versionNumber?: string;
    revisionNumber?: string;
    versionDate?: string;
    shortName?: string;
    conceptType?: string;
    note?: string;
    remark?: string;
    definition?: { [key: string]: string; };
    comment?: { [key: string]: string; };
    languages?: Array<ConceptBaseLanguages>;
    preferredLabel?: { [key: string]: string; };
    alternateLabel?: { [key: string]: Array<string>; };
    hiddenLabel?: { [key: string]: Array<string>; };
}
export namespace ConceptBase {
    export type IdTypeEnum = 'IRI' | 'IRDI';
    export const IdTypeEnum = {
        IRI: 'IRI' as IdTypeEnum,
        IRDI: 'IRDI' as IdTypeEnum
    };
}