/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptBase } from './conceptBase';
import { ConceptBaseLanguages } from './conceptBaseLanguages';

/**
 * The full description for the concept class
 */
export interface ConceptClass extends ConceptBase { 
    level?: number;
    codedName?: string;
    category?: string;
    parentElement?: ConceptClass;
}
export namespace ConceptClass {
}