/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdministrativeInformation } from './administrativeInformation';
import { DataSpecificationContent } from './dataSpecificationContent';
import { LangString } from './langString';

export interface DataSpecification { 
    id?: string;
    dataSpecificationContent?: DataSpecificationContent;
    administration?: AdministrativeInformation;
    descriptions?: Array<LangString>;
}