/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptClass } from './conceptClass';
import { ConceptProperty } from './conceptProperty';
import { ConceptPropertyUnit } from './conceptPropertyUnit';
import { ConceptPropertyValue } from './conceptPropertyValue';

export type InlineResponse200 = ConceptClass | ConceptProperty | ConceptPropertyUnit | ConceptPropertyValue;