/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Key { 
    value?: string;
    type?: Key.TypeEnum;
}
export namespace Key {
    export type TypeEnum = 'AnnotatedRelationshipElement' | 'AssetAdministrationShell' | 'BasicEventElement' | 'Blob' | 'Capability' | 'ConceptDescription' | 'DataElement' | 'Entity' | 'EventElement' | 'File' | 'FragmentReference' | 'GlobalReference' | 'Identifiable' | 'MultiLanguageProperty' | 'Operation' | 'Property' | 'Range' | 'Referable' | 'ReferenceElement' | 'RelationshipElement' | 'Submodel' | 'SubmodelElement' | 'SubmodelElementCollection' | 'SubmodelElementList';
    export const TypeEnum = {
        AnnotatedRelationshipElement: 'AnnotatedRelationshipElement' as TypeEnum,
        AssetAdministrationShell: 'AssetAdministrationShell' as TypeEnum,
        BasicEventElement: 'BasicEventElement' as TypeEnum,
        Blob: 'Blob' as TypeEnum,
        Capability: 'Capability' as TypeEnum,
        ConceptDescription: 'ConceptDescription' as TypeEnum,
        DataElement: 'DataElement' as TypeEnum,
        Entity: 'Entity' as TypeEnum,
        EventElement: 'EventElement' as TypeEnum,
        File: 'File' as TypeEnum,
        FragmentReference: 'FragmentReference' as TypeEnum,
        GlobalReference: 'GlobalReference' as TypeEnum,
        Identifiable: 'Identifiable' as TypeEnum,
        MultiLanguageProperty: 'MultiLanguageProperty' as TypeEnum,
        Operation: 'Operation' as TypeEnum,
        Property: 'Property' as TypeEnum,
        Range: 'Range' as TypeEnum,
        Referable: 'Referable' as TypeEnum,
        ReferenceElement: 'ReferenceElement' as TypeEnum,
        RelationshipElement: 'RelationshipElement' as TypeEnum,
        Submodel: 'Submodel' as TypeEnum,
        SubmodelElement: 'SubmodelElement' as TypeEnum,
        SubmodelElementCollection: 'SubmodelElementCollection' as TypeEnum,
        SubmodelElementList: 'SubmodelElementList' as TypeEnum
    };
}