/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Message { 
    code?: string;
    messageType?: Message.MessageTypeEnum;
    text?: string;
    timestamp?: string;
}
export namespace Message {
    export type MessageTypeEnum = 'Undefined' | 'Info' | 'Warning' | 'Error' | 'Exception';
    export const MessageTypeEnum = {
        Undefined: 'Undefined' as MessageTypeEnum,
        Info: 'Info' as MessageTypeEnum,
        Warning: 'Warning' as MessageTypeEnum,
        Error: 'Error' as MessageTypeEnum,
        Exception: 'Exception' as MessageTypeEnum
    };
}