/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperationVariable } from './operationVariable';
import { Result } from './result';

export interface OperationResult { 
    executionResult?: Result;
    executionState?: OperationResult.ExecutionStateEnum;
    inoutputArguments?: Array<OperationVariable>;
    outputArguments?: Array<OperationVariable>;
    requestId?: string;
}
export namespace OperationResult {
    export type ExecutionStateEnum = 'Initiated' | 'Running' | 'Completed' | 'Canceled' | 'Failed' | 'Timeout';
    export const ExecutionStateEnum = {
        Initiated: 'Initiated' as ExecutionStateEnum,
        Running: 'Running' as ExecutionStateEnum,
        Completed: 'Completed' as ExecutionStateEnum,
        Canceled: 'Canceled' as ExecutionStateEnum,
        Failed: 'Failed' as ExecutionStateEnum,
        Timeout: 'Timeout' as ExecutionStateEnum
    };
}