/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperationVariable } from './operationVariable';

/**
 * Operation request object
 */
export interface OperationRequest { 
    inoutputArguments?: Array<OperationVariable>;
    inputArguments?: Array<OperationVariable>;
    requestId?: string;
    timeout?: number;
}