/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Reference } from './reference';

export interface Permission { 
    permission?: Reference;
    kindOfPermission?: Permission.KindOfPermissionEnum;
}
export namespace Permission {
    export type KindOfPermissionEnum = 'Allow' | 'Deny' | 'NotApplicable' | 'Undefined';
    export const KindOfPermissionEnum = {
        Allow: 'Allow' as KindOfPermissionEnum,
        Deny: 'Deny' as KindOfPermissionEnum,
        NotApplicable: 'NotApplicable' as KindOfPermissionEnum,
        Undefined: 'Undefined' as KindOfPermissionEnum
    };
}