/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObjectAttributes } from './objectAttributes';
import { Permission } from './permission';
import { Reference } from './reference';

export interface PermissionsPerObject { 
    permissions?: Array<Permission>;
    object?: Reference;
    targetObjectAttributes?: ObjectAttributes;
}