/**
 * the Info
 * infodescription
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Referable } from '../model/referable';
import { Reference } from '../model/reference';
import { Submodel } from '../model/submodel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SubmodelRepositoryInterfaceConnectorService {

    protected basePath = '{protocol}://{server}:{port}/{path}';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Obtain a referable element by reference
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getReferableElement(body: Reference, observe?: 'body', reportProgress?: boolean): Observable<Referable>;
    public getReferableElement(body: Reference, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Referable>>;
    public getReferableElement(body: Reference, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Referable>>;
    public getReferableElement(body: Reference, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getReferableElement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Referable>('post',`${this.basePath}/subrepo/reference`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtain the submodel based on it&#x27;s identifier from the repository
     * 
     * @param submodelIdentifier The Submodel’s unique id (UTF8-BASE64-URL-encoded)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubmodel(submodelIdentifier: string, observe?: 'body', reportProgress?: boolean): Observable<Submodel>;
    public getSubmodel(submodelIdentifier: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Submodel>>;
    public getSubmodel(submodelIdentifier: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Submodel>>;
    public getSubmodel(submodelIdentifier: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (submodelIdentifier === null || submodelIdentifier === undefined) {
            throw new Error('Required parameter submodelIdentifier was null or undefined when calling getSubmodel.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Submodel>('get',`${this.basePath}/subrepo/${encodeURIComponent(String(submodelIdentifier))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtain a referable element by refernence
     * 
     * @param submodelIdentifier The Asset Administration Shell’s unique id (UTF8-BASE64-URL-encoded)
     * @param path The path to the requested element
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubmodelElement(submodelIdentifier: string, path: string, observe?: 'body', reportProgress?: boolean): Observable<Referable>;
    public getSubmodelElement(submodelIdentifier: string, path: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Referable>>;
    public getSubmodelElement(submodelIdentifier: string, path: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Referable>>;
    public getSubmodelElement(submodelIdentifier: string, path: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (submodelIdentifier === null || submodelIdentifier === undefined) {
            throw new Error('Required parameter submodelIdentifier was null or undefined when calling getSubmodelElement.');
        }

        if (path === null || path === undefined) {
            throw new Error('Required parameter path was null or undefined when calling getSubmodelElement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Referable>('get',`${this.basePath}/subrepo/${encodeURIComponent(String(submodelIdentifier))}/submodel/submodel-elements/${encodeURIComponent(String(path))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtain the submodel references from the repository
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubmodels(observe?: 'body', reportProgress?: boolean): Observable<Array<Reference>>;
    public getSubmodels(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Reference>>>;
    public getSubmodels(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Reference>>>;
    public getSubmodels(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Reference>>('get',`${this.basePath}/subrepo`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtain the value of the (Data)Element
     * 
     * @param submodelIdentifier The Asset Administration Shell’s unique id (UTF8-BASE64-URL-encoded)
     * @param path The path to the requested element
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getValue(submodelIdentifier: string, path: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getValue(submodelIdentifier: string, path: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getValue(submodelIdentifier: string, path: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getValue(submodelIdentifier: string, path: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (submodelIdentifier === null || submodelIdentifier === undefined) {
            throw new Error('Required parameter submodelIdentifier was null or undefined when calling getValue.');
        }

        if (path === null || path === undefined) {
            throw new Error('Required parameter path was null or undefined when calling getValue.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/plain'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/subrepo/${encodeURIComponent(String(submodelIdentifier))}/submodel/submodel-elements/${encodeURIComponent(String(path))}/value`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtain the value of a referable element by reference
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getValueByReference(body: Reference, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getValueByReference(body: Reference, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getValueByReference(body: Reference, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getValueByReference(body: Reference, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getValueByReference.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/subrepo/reference/value`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
